<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VMT.ERP.Common\VMT.ERP.Common.csproj" />
    <ProjectReference Include="..\VMT.ERP.Domain\VMT.ERP.Domain.csproj" />
    <ProjectReference Include="..\VMT.ERP.Persistence\VMT.ERP.Persistence.csproj" />
    <ProjectReference Include="..\VMT.ERP.Utils\VMT.ERP.Utils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Bll\Security\Register\" />
  </ItemGroup>

</Project>
